### ISSUE TITLE
Add support for Libra Colour and Clara Colour

### ISSUE THREAD

**Issue by azw413** [baskerville/plato#364]
It installs ok and is visible in NickelMenu but when you launch it, the devices freezes and needs a hard reboot to get going again.

**Comment by ZNielsen** [comment]
Same behavior on Clara BW

**Comment by baskerville** [comment]
The _Clara BW_ should be working on the _master_ branch. The color models will require more work.

**Comment by mullse01** [comment]
I am still having trouble with my Clara BW (v4.39.22861) - neither the one-click packages, nor the installing manually via the master branch here, results in a successful launch of Plato. Launching with either KFMon or directly via Nickel Menu causes the device to hang until manually rebooted.

**Comment by ZNielsen** [comment]
@baskerville, would you mind cutting a release when you get a chance? I went to build the master branch but it looks like the Kobo-Reader org has hit the bandwidth limit for git-lfs, so I can't download the toolchains.

**Comment by ZNielsen** [comment]
You can scratch that request — I pulled out an old pi to build with

**Comment by stilktf** [comment]
Yeah, doesn't seem like Plato works on my Clara BW either. Tried master and all that, still won't work :/

**Comment by ashrude** [comment]
Same issue on Kobo Clara Colour

**Comment by leogott** [comment]
Anything people owning Colour kobos can do to help?

**Comment by Usuario6** [comment]
Same here on Libra Colour

**Comment by InfinityCg** [comment]
Are there plans to support a version for the Libra color?

**Comment by amatya-aditya** [comment]
Any support for Kobo Libra Color?

**Comment by baskerville** [comment]
Here's a test binary for the new color devices. The existing files in `.adds/plato` have to be overwritten with the content of this archive. If you already have a *Settings.toml* file, remove the line that starts with `color = ` in the `[sketch.pen]` section before launching. In the main menu (last icon in the top bar), select *Applications → Rotation Values* and post the content of *info.log* in your comment.

[plato-color_devices-01.zip](https://github.com/user-attachments/files/17850181/plato-color_devices-01.zip)

**Comment by InfinityCg** [comment]
> Here's a test binary for the new color devices. The existing files in `.adds/plato` have to be overwritten with the content of this archive. If you already have a _Settings.toml_ file, remove the line that starts with `color = ` in the `[sketch.pen]` section before launching. In the main menu (last icon in the top bar), select _Applications → Rotation Values_ and post the content of _info.log_ in your comment.
> 
> [plato-color_devices-01.zip](https://github.com/user-attachments/files/17850181/plato-color_devices-01.zip)

`OK
Plato is running on a Kobo Libra Colour.
The framebuffer resolution is 1264 by 1680.
Framebuffer rotation: 0 -> 0.
Framebuffer rotation: 1 -> 1.
Framebuffer rotation: 0 -> 0.
Framebuffer rotation: 1 -> 1.
Tap (1594, 106) (1264, 1680)
Tap (1582, 1187) (1264, 1680)
Tap (115, 1148) (1264, 1680)
Tap (142, 107) (1264, 1680)
Framebuffer rotation: 0 -> 0.
Gyro rotation: 0
Tap (116, 88) (1680, 1264)
Framebuffer rotation: 1 -> 1.
Gyro rotation: 1
Tap (1581, 114) (1264, 1680)
Framebuffer rotation: 2 -> 2.
Gyro rotation: 2
Tap (1598, 1165) (1680, 1264)
Framebuffer rotation: 3 -> 3.
Gyro rotation: 3
Tap (109, 1158) (1264, 1680)
Framebuffer rotation: 1 -> 1.
Startup rotation: 1.
Mirroring scheme: (2, 1).
Framebuffer rotation: 2 -> 2.
fsck.fat 4.1+git (2017-01-24)
0x41: Dirty bit is set. Fs was not properly unmounted and some data may be corrupt.
 Automatically removing dirty bit.
/dev/mmcblk0p12: 2449 files, 40303/1771354 clusters
fsck.fat 4.1+git (2017-01-24)
/dev/mmcblk0p12: 2449 files, 40303/1771354 clusters`

**Comment by jwillikers** [comment]
```
OK
Plato is running on a Kobo Libra Colour.
The framebuffer resolution is 1264 by 1680.
Framebuffer rotation: 1 -> 1.
Tap (1560, 107) (1264, 1680)
Tap (1602, 1166) (1264, 1680)
Tap (102, 1174) (1264, 1680)
Tap (84, 78) (1264, 1680)
Framebuffer rotation: 0 -> 0.
Tap (99, 74) (1680, 1264)
Framebuffer rotation: 1 -> 1.
Tap (1598, 93) (1264, 1680)
Framebuffer rotation: 2 -> 2.
Tap (1585, 1174) (1680, 1264)
Framebuffer rotation: 3 -> 3.
Tap (92, 1193) (1264, 1680)
Framebuffer rotation: 1 -> 1.
Startup rotation: 1.
Mirroring scheme: (2, 1).
Tap (1558, 110) (1264, 1680)
Tap (1572, 1172) (1264, 1680)
Tap (125, 1189) (1264, 1680)
Tap (84, 80) (1264, 1680)
Framebuffer rotation: 0 -> 0.
Tap (101, 114) (1680, 1264)
Framebuffer rotation: 1 -> 1.
Tap (1579, 92) (1264, 1680)
Framebuffer rotation: 2 -> 2.
Tap (1592, 1150) (1680, 1264)
Framebuffer rotation: 3 -> 3.
Tap (121, 1195) (1264, 1680)
Framebuffer rotation: 1 -> 1.
Startup rotation: 1.
Mirroring scheme: (2, 1).
```

**Comment by amatya-aditya** [comment]
Failed to connect to non-global ctrl_ifname: wlan0  error: No such file or directory
ifconfig: SIOCGIFFLAGS: No such device
Plato is running on a Kobo Libra Colour.
The framebuffer resolution is 1264 by 1680.
Tap (1556, 99) (1264, 1680)
Tap (1560, 1167) (1264, 1680)
Tap (115, 125) (1264, 1680)
Tap (86, 1150) (1264, 1680)
Framebuffer rotation: 0 -> 0.
Gyro rotation: 0
Tap (129, 76) (1680, 1264)
Framebuffer rotation: 1 -> 1.
Tap (1608, 149) (1264, 1680)
Framebuffer rotation: 2 -> 2.
Tap (1624, 1168) (1680, 1264)
Framebuffer rotation: 3 -> 3.
Tap (69, 1116) (1264, 1680)
Framebuffer rotation: 1 -> 1.
Startup rotation: 1.
Mirroring scheme: (2, 1).

**Comment by baskerville** [comment]
Thanks, it seems the parameters are already fine for the _Libra Colour_. We need a tester for the _Clara Colour_ now.

**Comment by IcingTomato** [comment]
[info.log](https://github.com/user-attachments/files/17853867/info.log)
Hi, @baskerville ! I tested the new file you uploaded with my Libre Colour. It works, but not very well, the color display seems to be reversed, and it restarts when it encounters some large epub files.
![{BC2719AF-6DE8-4D95-907B-7866305DA1CE}](https://github.com/user-attachments/assets/bcbd8047-399c-4ac3-b7af-3a863ba69235)
and here is the correct colour:
![{1FE93300-68E7-4ADC-83AA-F63929627C76}](https://github.com/user-attachments/assets/2ec6e227-e22f-452d-9d81-4471ccd7128b)

**Comment by InfinityCg** [comment]
>I tested the new file you uploaded with my Libra Colour. It works, but not very well, the color display seems to be reversed, and it restarts when it encounters some large epub files.

This + this kind of blue seems very prevalent, Most of my colors are being rendered as this blue or earth/clay red, green renders fine (I think)

**Comment by jwillikers** [comment]
I noticed the same thing. Green does render much better than other colors.

**Comment by baskerville** [comment]
The attached binary should fix the color components mix-up.

[plato-color_devices-02.zip](https://github.com/user-attachments/files/17871346/plato-color_devices-02.zip)

**Comment by IcingTomato** [comment]
![image](https://github.com/user-attachments/assets/babe1268-50e9-469e-b573-efaabe4b90d0)
Now it works very well! Thank you!

**Comment by ashrude** [comment]
@baskerville Just loaded it on my Clara Colour using your second binary, seems to work well, and the colours do display properly. I'll play around with it a bit tonight, let me know if there's anything you want me to test

**Comment by baskerville** [comment]
> let me know if there's anything you want me to test

In the main menu (last icon in the top bar), select *Applications → Rotation Values* and post the content of *info.log* in your comment.

**Comment by IcingTomato** [comment]
Hi, @baskerville ! Here is the info.log in my Libra Colour:
```shell
Tap (1595, 105) (1264, 1680)
Tap (1571, 1138) (1264, 1680)
Tap (102, 1177) (1264, 1680)
Tap (107, 75) (1264, 1680)
Framebuffer rotation: 0 -> 0.
Gyro rotation: 0
Tap (108, 126) (1680, 1264)
Framebuffer rotation: 1 -> 1.
Gyro rotation: 1
Tap (1581, 76) (1264, 1680)
Framebuffer rotation: 2 -> 2.
Gyro rotation: 2
Tap (1587, 1153) (1680, 1264)
Framebuffer rotation: 3 -> 3.
Gyro rotation: 3
Tap (101, 1165) (1264, 1680)
Framebuffer rotation: 1 -> 1.
Startup rotation: 1.
Mirroring scheme: (2, 1).
```

**Comment by yodatak** [comment]
Thanks for the work if you need to have a device to test @baskerville  i think we could make a crowd founding and to thanks you for working on this thanks !

**Comment by ashrude** [comment]
```
Plato is running on a Kobo Clara Colour.
The framebuffer resolution is 1072 by 1448.
Tap (66, 986) (1072, 1448)
Tap (89, 68) (1072, 1448)
Tap (1374, 86) (1072, 1448)
Tap (1371, 1029) (1072, 1448)
Framebuffer rotation: 0 -> 0.
Tap (65, 69) (1448, 1072)
Framebuffer rotation: 1 -> 1.
Tap (1360, 110) (1072, 1448)
Framebuffer rotation: 2 -> 2.
Tap (1365, 998) (1448, 1072)
Framebuffer rotation: 3 -> 3.
Tap (93, 986) (1072, 1448)
Framebuffer rotation: 3 -> 3.
Startup rotation: 3.
Mirroring scheme: (2, 1).
```

**Comment by baskerville** [comment]
> Thanks for the work if you need to have a device to test @baskerville i think we could make a crowd founding and to thanks you for working on this thanks !

Thanks, but I'm relying on _KOReader_, _FBInk_, and _KoboUSBMS_ to understand the new devices. So most of the work is done by others.
